### ISSUE TITLE
Install the plugin with logstash docker image

### ISSUE THREAD

**Issue by alirezasafi** [revpoint/logstash-codec-avro_schema_registry#27]
Is there a way to install this plugin when using docker image logstash?
the compose are just like that.
```
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.2
    restart: unless-stopped
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash
```
